Repository JuliaGPU/CuArrays.jl, pull requests merged in 2019-10, with the labels that each got.

#446 Implement findall
  src/accumulate.jl
  src/indexing.jl
  test/base.jl
Labels: performance

#447 Optimize accumulate
  src/accumulate.jl
  src/indexing.jl
  src/subarray.jl
  test/base.jl
Labels: performance

#455 Prevent CPU to GPU copy in mapreduce.
  src/mapreduce.jl
Labels: bug

#457 Adapt to CUDAdrv.jl#167
  .gitlab-ci.yml
  Manifest.toml
  src/array.jl
  src/blas/highlevel.jl
  src/blas/linalg.jl
  src/gpuarray_interface.jl
  src/memory.jl
  src/memory/binned.jl
  src/memory/dummy.jl
  src/memory/simple.jl
  src/memory/split.jl
  src/subarray.jl
  test/base.jl
  test/forwarddiff.jl
Labels: enhancement, performance

#464 Fix #463
  res/wrap/pointers.json
  src/dnn/libcudnn.jl
  test/dnn.jl
Labels: bug

#441 More memory allocator improvements
  src/memory/binned.jl
  src/memory/dummy.jl
  src/memory/simple.jl
  src/memory/split.jl
Labels: performance

#461 Add a strided batched method for getrf
  src/blas/highlevel.jl
  test/blas.jl
Labels: performance
