Repository JuliaGPU/CuArrays.jl, pull requests merged in 2019-09, with the labels that each got.

#330 cuTENSOR wrappers
  Project.toml
  src/CuArrays.jl
  src/blas/libcublas.jl
  src/blas/libcublas_types.jl
  src/tensor/CUTENSOR.jl
  src/tensor/error.jl
  src/tensor/highlevel.jl
  src/tensor/libcutensor.jl
  src/tensor/libcutensor_types.jl
  src/tensor/wrappers.jl
  test/dnn.jl
  test/runtests.jl
  test/tensor.jl
Labels: enhancement

#416 ND-reverse
  src/array.jl
  test/base.jl
Labels: enhancement

#427 Fixes to split memory pool
  .gitlab-ci.yml
  src/memory.jl
  src/memory/binned.jl
  src/memory/split.jl
Labels: bug, performance

#366 Work around / ignore cuFFT issues.
  res/wrap/wrap.jl
  src/fft/error.jl
  src/fft/fft.jl
  src/fft/libcufft.jl
  test/fft.jl
  test/util.jl
Labels: bug

#434 Use CuArrays.zeros instead of broadcasting.
  src/solver/dense.jl
  src/solver/highlevel.jl
Labels: enhancement

#433 Synchronize the GPU while doing time measurements.
  src/memory.jl
Labels: enhancement

#404 WIP: CUDNN improvements
  .gitlab-ci.yml
  src/CuArrays.jl
  src/array.jl
  src/blas/CUBLAS.jl
  src/deprecated.jl
  src/dnn/CUDNN.jl
  src/dnn/activation.jl
  src/dnn/base.jl
  src/dnn/batchnorm.jl
  src/dnn/conv.jl
  src/dnn/dropout.jl
  src/dnn/filter.jl
  src/dnn/helpers.jl
  src/dnn/libcudnn.jl
  src/dnn/libcudnn_common.jl
  src/dnn/libcudnn_types.jl
  src/dnn/nnlib.jl
  src/dnn/pooling.jl
  src/dnn/rnn.jl
  src/dnn/softmax.jl
  src/dnn/tensor.jl
  src/linalg.jl
  src/memory/binned.jl
  src/memory/dummy.jl
  src/memory/simple.jl
  src/memory/split.jl
  src/nnlib.jl
  src/permuteddimsarray.jl
  src/solver/CUSOLVER.jl
  src/solver/dense.jl
  src/solver/sparse.jl
  src/sparse/CUSPARSE.jl
  src/sparse/linalg.jl
Labels: enhancement

#436 Use the memory pool for CUFFT workarea allocation.
  src/fft/CUFFT.jl
  src/fft/fft.jl
Labels: enhancement
