Repository JuliaGPU/CuArrays.jl, pull requests merged in 2020-05, with the labels that each got.

#704 Repopulate the pool from freed blocks before allocating.
  src/memory/binned.jl
Labels: performance

#708 Add mul! for trmm! and tests.
  src/blas/linalg.jl
  test/blas.jl
Labels: enhancement

#711 Perform threaded test in lock.
  test/base.jl
Labels: bugfix

#712 findfirst should return nothing if no matching element is found
  src/indexing.jl
  test/base.jl
Labels: bugfix

#717 fix ambiguity for Random.seed!(rng, nothing)
  src/rand/random.jl
  test/rand.jl
Labels: bugfix

#718 Actually put the workspace buffer back in the memory pool.
  src/utils.jl
Labels: performance
