Repository JuliaGPU/CuArrays.jl, pull requests merged in 2020-03, with the labels that each got.

#627 Thread safety of memory allocator
  .gitlab-ci.yml
  Manifest.toml
  src/memory.jl
  src/memory/binned.jl
  src/memory/dummy.jl
  src/memory/simple.jl
  src/memory/split.jl
  test/base.jl
  test/runtests.jl
Labels: enhancement

#634 Provide 5-arg mul!
  src/blas/linalg.jl
  test/blas.jl
Labels: needs tests

#650 Fix and test initialization without CUDA.
  .gitlab-ci.yml
  src/CuArrays.jl
Labels: bugfix

#663 Implement GPUArrays vararg mapreduce.
  Manifest.toml
  src/mapreduce.jl
Labels: performance
